[package]
name = "cpl-rust"
version = "0.1.0"
authors = ["yaumu3 <yumu@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.6.5"
